// <auto-generated />
namespace StarFishWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migration2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration2));
        
        string IMigrationMetadata.Id
        {
            get { return "201905142334422_migration2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
